### ISSUE TITLE
Module not found: Can't resolve 'components/App' in path/to/blog-frontend/src

### ISSUE THREAD

**Issue by kensixx** [keumtae-kim/spring-boot-react-blog#2]
Hi keumtae-kim,

I've been trying to run your project for educational purposes.
I want to gain knowledge on using Spring REST together with React as its front-end.

I want specifically learn by creating creating a blog app.

I think this fits it the most. I think I'll try to learn from your source code. Thank you for this.

However, I can't seem to run the app after doing a `yarn start` command. I think the maven dependencies and yarn dependencies went well.. so far..

I replaced the Java 11 to Java 8 by the way, because that's what I have for now.

Is there something I'm missing?

Thank you very much in advance!

Kind regards,
Ken

Edit: Attached image for reference.
![image](https://user-images.githubusercontent.com/24205790/49911583-ef326280-fec1-11e8-8a8b-caad701f595e.png)

**Comment by keumtae-kim** [comment]
Hi, kensixx,

I made a mistake not to commit the .env file.
Because it was included in the ingore list in the .gitignore.
I'm sorry. Please git pull and try again.

Best Regards,
Kim Keumtae.

**Comment by kensixx** [comment]
I can now access the homepage without facing any issues. Thank you very much!

However, I just noticed that the Delete button has no function, it just redirects to the homepage.

I don't have any problems regarding that, I just want to clarify if this is really the current scenario. 

Regards,
Ken Flake

**Comment by keumtae-kim** [comment]
Sorry for the delay.
The post delete api  was not implemented.
It is currently available.
