### ISSUE TITLE
restcontroller 추가 후 실행 시 Whitelabel Error Page 에러

### ISSUE THREAD

**Issue by Ta2Rim** [keumtae-kim/spring-boot-react-blog#5]
![image](https://user-images.githubusercontent.com/41318449/59739063-647e5600-929e-11e9-8341-41037d28be1a.png)
블로그에 적혀진대로 맵핑메소드를 하나 추가하여 실행해보았는데요

![image](https://user-images.githubusercontent.com/41318449/59739028-53354980-929e-11e9-9775-25762eb2cd66.png)
다음과 같은 에러가 발생합니다.

**Comment by Ta2Rim** [comment]
아하 제가 이해를 잘못했네요. 프론트서버를띄워서 정해진 api만 호출하면되는거군요 좋은예제 감사합니다.

**Comment by keumtae-kim** [comment]
@Ta2Rim 
WebSecurityConfig.java에 보시면 스프링 시큐리티를 이용해서 허용된 요청 외의 요청은 인증 필터를 거치게 되어있습니다. 인증 정보가 없다면 401 Unauthorized 에러가 발생합니다.

```
                .antMatchers(HttpMethod.GET, "/api/posts/**").permitAll()
                .antMatchers(HttpMethod.GET, "/api/comments/**").permitAll()
                .antMatchers("/", "/error", "/api/authenticate/**", "/api/register", "/auth/authenticate"
                        , "/auth/signup", "/oauth2/**", "/h2-console/**", "/swagger-ui.html")
                .permitAll()
                .anyRequest()
                .authenticated()
```
